apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: Container Registry Access
      containers:
        - name: demo-app
          image: ghcr.io/bhhgtr/demo-app:latest
          ports:
            - containerPort: 3000
            
