apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: demo-app
          image: ghcr.io/bhhgtr/demo-app:a098efbdbe6f694ab602cbd9b2c9ec0959838807
          ports:
            - containerPort: 3000
            

