apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: ghcr.io/bhhgtr/demo-app:f54b8cf495d83d0d19156e8fee6ad8346a9e5d46
          ports:
            - containerPort: 3000
